name: Ballchasing on‑demand

on: { workflow_dispatch: {} }

permissions:
  contents: write            # allow pushes & release uploads

jobs:
  pull-and-publish:
    runs-on: ubuntu-latest
    env:
      BC_TOKEN:       ${{ secrets.BC_TOKEN }}
      BC_GROUP_ID:    ${{ secrets.BC_GROUP_ID }}
      BC_PLAYER_NAME: ${{ secrets.BC_PLAYER_NAME }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - run: pip install -r requirements.txt
      - run: python download_stats.py

      - run: sudo apt-get update && sudo apt-get install -y zip

      - name: Pack stats.zip
        run: |
          rm -f stats.zip
          if [ -d stats ]; then
            zip -qr stats.zip stats
          fi

      - name: Upload artefacts to release
        uses: softprops/action-gh-release@v1
        env: { GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} }
        with:
          tag_name: latest-data
          name: Latest RL Stats
          draft: false
          files: |
            stats.zip
            summary.csv
          generate_release_notes: false
          prerelease: false

      - name: Commit updated CSV
        uses: EndBug/add-and-commit@v9
        with:
          message: "Automated stats update"
          add: "summary.csv"
          allow_empty: true

      - name: Print CSV head
        run: head -n 5 summary.csv || true
