name: Ballchasing on‑demand

on:
  workflow_dispatch: {}

permissions:
  contents: write          # allow the token to push commits & create releases

jobs:
  pull-and-publish:
    runs-on: ubuntu-latest

    env:
      BC_TOKEN:       ${{ secrets.BC_TOKEN }}
      BC_GROUP_ID:    ${{ secrets.BC_GROUP_ID }}
      BC_PLAYER_NAME: ${{ secrets.BC_PLAYER_NAME }}

    steps:
      # 1 ▸ Check out repo
      - uses: actions/checkout@v4

      # 2 ▸ Python 3.11
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3 ▸ Install dependencies
      - run: pip install -r requirements.txt

      # 4 ▸ Pull replays → summary.csv + stats/*.json
      - run: python download_stats.py

      # 5 ▸ Ensure zip tool
      - run: sudo apt-get update && sudo apt-get install -y zip

      # 6 ▸ Zip JSON folder (if it exists)
      - name: Pack stats.zip
        run: |
          rm -f stats.zip
          if [ -d stats ]; then
            zip -qr stats.zip stats
          fi

      # 7 ▸ Upload CSV + ZIP to published release “latest-data”
      - name: Upload artefacts to release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest-data
          name: Latest RL Stats
          draft: false                 # ensure it’s published
          prerelease: false            # not a pre‑release
          files: |
            stats.zip
            summary.csv
          generate_release_notes: false

      # 8 ▸ Commit summary.csv back to repo (ZIP lives only in release)
      - name: Commit updated CSV
        uses: EndBug/add-and-commit@v9
        with:
          message: "Automated stats update"
          add: summary.csv
          empty_commit: true           # succeed even if no changes

      # 9 ▸ Show a preview in logs (optional)
      - name: Print CSV head
        run: head -n 5 summary.csv || true
