name: Ballchasing on‑demand

on:
  workflow_dispatch: {}

permissions:
  contents: write          # let the token push commits & create releases

jobs:
  pull-and-publish:
    runs-on: ubuntu-latest

    env:
      BC_TOKEN:       ${{ secrets.BC_TOKEN }}
      BC_GROUP_ID:    ${{ secrets.BC_GROUP_ID }}
      BC_PLAYER_NAME: ${{ secrets.BC_PLAYER_NAME }}

    steps:
      # 1 ▸ Check out repo
      - uses: actions/checkout@v4

      # 2 ▸ Python 3.11
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3 ▸ Install Python dependencies
      - run: pip install -r requirements.txt

      # 4 ▸ Pull replays → summary.csv + stats/*.json
      - run: python download_stats.py

      # 5 ▸ Ensure zip tool
      - run: sudo apt-get update && sudo apt-get install -y zip

      # 6 ▸ Zip JSON folder (if it exists)
      - name: Pack stats.zip
        run: |
          rm -f stats.zip
          if [ -d stats ] && [ "$(ls -A stats)" ]; then
            zip -qr stats.zip stats
          else
            echo "No JSON files to zip"
          fi

      # 7 ▸ Upload CSV + ZIP to published release “latest-data”
      - name: Upload artefacts to release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest-data
          name: Latest RL Stats
          draft: false
          prerelease: false
          files: |
            stats.zip
            summary.csv
          generate_release_notes: false

      # 8 ▸ Commit summary.csv + stats.zip back to the repo
      - name: Commit updated artefacts
        uses: EndBug/add-and-commit@v9
        with:
          message: "Automated stats update"
          add: |
            summary.csv
            stats.zip
          commit: '--allow-empty'     # succeed even if nothing changed

      # 9 ▸ Show first 5 lines in log (optional)
      - name: Print CSV head
        run: head -n 5 summary.csv || true
